/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CameraView: typeof import('./components/CameraView.vue')['default']
    Footbar: typeof import('./components/navigation/Footbar.vue')['default']
    Navbar: typeof import('./components/navigation/Navbar.vue')['default']
    ReadmeDialog: typeof import('./components/ReadmeDialog.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SimpleButton: typeof import('./components/shared/SimpleButton.vue')['default']
  }
}
